### PR TITLE
Also publish test artifacts

### PR DESCRIPTION
**Pull request by nightscape**
Hi Daniel,

for the talk it would be great if you could publish the test sources as well so I can use the example code from the test jar.
I'm just writing code to read BN definitions from bayes-scala and draw them in [spark-notebook](https://github.com/andypetrella/spark-notebook) using d3.
If all goes well I will show the provided examples in a nice graph :D

### CODE REVIEW

**Comment by danielkorzekwa** [comment]
done

On 7 April 2015 at 18:44, Martin Mauch <notifications@github.com> wrote:

> Hi Daniel,
>
> for the talk it would be great if you could publish the test sources as
> well so I can use the example code from the test jar.
> I'm just writing code to read BN definitions from bayes-scala and draw
> them in spark-notebook <https://github.com/andypetrella/spark-notebook>
> using d3.
> If all goes well I will show the provided examples in a nice graph :D
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/danielkorzekwa/bayes-scala/pull/22
> Commit Summary
>
>    - Also publish test artifacts
>
> File Changes
>
>    - *M* .travis.yml
>    <https://github.com/danielkorzekwa/bayes-scala/pull/22/files#diff-0>
>    (2)
>    - *M* publish.sbt
>    <https://github.com/danielkorzekwa/bayes-scala/pull/22/files#diff-1>
>    (2)
>
> Patch Links:
>
>    - https://github.com/danielkorzekwa/bayes-scala/pull/22.patch
>    - https://github.com/danielkorzekwa/bayes-scala/pull/22.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielkorzekwa/bayes-scala/pull/22>.
>



-- 
Daniel Korzekwa
Machine Learning Engineer
priv: https://www.linkedin.com/in/danielkorzekwa <http://danmachine.com/>
blog: http://blog.danmachine.com

**Comment by nightscape** [comment]
Nice, thanks! :)
I assume Travis will publish the test jars automatically in a while?

**Comment by nightscape** [comment]
Ah, in fact it already did: https://oss.sonatype.org/content/repositories/snapshots/com/github/danielkorzekwa/bayes-scala_2.11/0.5-SNAPSHOT/

All good :)

**Comment by danielkorzekwa** [comment]
already there
https://oss.sonatype.org/content/repositories/snapshots/com/github/danielkorzekwa/bayes-scala_2.10/0.5-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/com/github/danielkorzekwa/bayes-scala_2.11/0.5-SNAPSHOT/

On 7 April 2015 at 19:02, Martin Mauch <notifications@github.com> wrote:

> Nice, thanks! :)
> I assume Travis will publish the test jars automatically in a while?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielkorzekwa/bayes-scala/pull/22#issuecomment-90679696>
> .
>



-- 
Daniel Korzekwa
Machine Learning Engineer
priv: https://www.linkedin.com/in/danielkorzekwa <http://danmachine.com/>
blog: http://blog.danmachine.com

**Pull request merged**
